apiVersion: v1
kind: ReplicationController
metadata:
  name: emmie-v0.0.4
  labels:
    version: v0.0.4
spec:
  replicas: 1
  selector:
    name: emmie
    version: v0.0.4
  template:
    metadata:
      labels:
        name: emmie
        version: v0.0.4
    spec:
      containers:
      - name: emmie
        image: stevesloka/emmie:0.0.4
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        - -docker-registry=
        - -path-to-tokens=/etc/emmie-tokens/tokens.txt
        volumeMounts:
        - name: tokens
          mountPath: /etc/emmie-tokens
      volumes:
      - secret:
          secretName: emmie-tokens
        name: tokens
