apiVersion: v1
kind: ReplicationController
metadata:
  name: emmie-v0.0.1
  labels:
    version: v0.0.1
spec:
  replicas: 1
  selector:
    name: emmie
    version: v0.0.1
  template:
    metadata:
      labels:
        name: emmie
        version: v0.0.1
    spec:
      containers:
      - name: emmie
        image: stevesloka/emmie:latest
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        - -kubecfg-file=/etc/kubeconfig
        - -docker-registry=
        - -path-to-tokens=/etc/emmie-tokens/tokens.txt
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
        - name: tokens
          mountPath: /etc/emmie-tokens
      volumes:
      - hostPath:
          path: /var/lib/kubelet/kubeconfig
        name: kubeconfig
      - secret:
          secretName: emmie-tokens
        name: tokens
