apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-router
  namespace: deis
  labels:
    heritage: deis
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: deis-router
  template:
    metadata:
      labels:
        app: deis-router
    spec:
      containers:
      - name: deis-router
        image: quay.io/deis/router:v2.6.2
        imagePullPolicy: Always
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: tcp8080
          containerPort: 8080
        - name: tcp6443
          containerPort: 6443
        - name: tcp2222
          containerPort: 2222
        - name: tcp9090
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 1
          timeoutSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  name: deis-router
  namespace: deis
  labels:
    app: deis-router
spec:
  type: LoadBalancer
  ports:
    - name: tcp8080
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: tcp6443
      protocol: TCP
      port: 6443
      targetPort: 6443
    - name: tcp2222
      protocol: TCP
      port: 2222
      targetPort: 2222
    - name: tcp9090
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: deis-router
