apiVersion: v1
data:
  mysql-username: dXNlcg==
  mysql-root-password: cGFzc3dvcmQx
  mysql-user-password: cGFzc3dvcmQx
kind: Secret
metadata:
  name: mysql-creds
  namespace: template
type: Opaque

---

apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: db
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  namespace: template
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        ports:
          - name: db
            containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql-root-password
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-creds
                key: mysql-user-password
          - name: MYSQL_DATABASE
            value: demo_db
